version: '3.8'

services:
  om1_avatar:
    build:
      context: .
      dockerfile: Dockerfile
    image: openmindagi/om1_avatar:latest
    container_name: om1_avatar
    network_mode: host
    ports:
      - "4173:4173"
